import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Image as ImageIcon, MapPin, Sparkles } from 'lucide-react';
import { complaintApi, evidenceUrl } from '../services/api';
import ComparisonMetrics from '../components/ComparisonMetrics';
import { Complaint, Evidence } from '../types/complaint';

type PortalData = { complaint: Complaint; evidence: Evidence[]; comparison: any };

const PortalComplaintDetail: React.FC = () => {
  const { id, role } = useParams(); const worker = role === 'worker';
  const [data, setData] = useState<PortalData | null>(null); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [reviewStatus, setReviewStatus] = useState('');
  const navigate = useNavigate();
  const load = async () => { try { setData(await complaintApi.portalDetail(Number(id))); } catch (e: any) { setError(e.response?.data?.detail || 'Unable to load this complaint'); } };
  useEffect(() => { void load(); }, [id]);
  const uploadAfter = async () => { if (!file || !data) return; setBusy(true); try { await complaintApi.uploadEvidence(data.complaint.id, file, { type: 'AFTER', timestamp: new Date().toISOString(), latitude: data.complaint.latitude, longitude: data.complaint.longitude }); setFile(null); await load(); } catch (e: any) { setError(e.response?.data?.detail || 'Could not upload After photo'); } finally { setBusy(false); } };
  const runAiReview = async () => { if (!data) return; setBusy(true); setReviewStatus('Running live Gemini AI review…'); try { await complaintApi.verify(data.complaint.id); await load(); setReviewStatus('AI review completed.'); } catch (e: any) { setReviewStatus(e.response?.data?.detail || 'AI review could not be completed. Check the backend Gemini configuration.'); } finally { setBusy(false); } };
  if (error) return <div className="max-w-3xl mx-auto p-8"><Link to={worker ? '/worker' : '/public'} className="text-blue-600">← Back</Link><p className="mt-6 text-red-600">{error}</p></div>;
  if (!data) return <div className="p-10 text-center">Loading complaint…</div>;
  const before = data.evidence.filter(x => x.type === 'BEFORE'); const after = data.evidence.filter(x => x.type === 'AFTER'); const latestBefore = before[before.length - 1]; const latestAfter = after[after.length - 1];
  return <div className="max-w-5xl mx-auto p-6 space-y-6"><Link to={worker ? '/worker' : '/public'} className="text-blue-600 text-sm flex gap-1 items-center"><ArrowLeft className="w-4 h-4"/> Back to {worker ? 'worker' : 'public'} dashboard</Link><header><p className="font-bold text-sm text-blue-600">{worker ? 'WORKER' : 'PUBLIC'} COMPLAINT VIEW</p><h1 className="text-3xl font-bold">{data.complaint.complaint_number}</h1><p className="mt-2 capitalize text-slate-600">{data.complaint.issue_type.replace(/_/g, ' ')} · {data.complaint.status.replace(/_/g, ' ')}</p><p className="text-slate-500 flex gap-1 mt-1"><MapPin className="w-4 h-4"/>{data.complaint.address}</p></header><div className="grid md:grid-cols-2 gap-5"><section className="bg-white rounded-xl border p-5"><h2 className="font-bold flex gap-2"><ImageIcon className="w-5 h-5"/> Before evidence</h2>{latestBefore ? <img className="mt-4 w-full aspect-video object-cover rounded-lg" src={evidenceUrl(latestBefore.file_path, latestBefore.id)} alt="Before evidence"/> : <p className="mt-4 text-slate-500">No Before photo available.</p>}</section><section className="bg-white rounded-xl border p-5"><h2 className="font-bold flex gap-2"><ImageIcon className="w-5 h-5"/> Worker After evidence</h2>{latestAfter ? <img className="mt-4 w-full aspect-video object-cover rounded-lg" src={evidenceUrl(latestAfter.file_path, latestAfter.id)} alt="After evidence"/> : <p className="mt-4 text-slate-500">The worker has not submitted an After photo yet.</p>}{worker && <div className="mt-4 border-t pt-4"><p className="text-sm font-medium">Submit work-completion photo</p><input type="file" accept="image/*" className="mt-2" onChange={e => setFile(e.target.files?.[0] || null)}/><button disabled={!file || busy} onClick={uploadAfter} className="mt-3 bg-orange-600 text-white rounded px-4 py-2 font-bold disabled:opacity-50">{busy ? 'Submitting…' : 'Upload After photo & start AI review'}</button></div>}</section></div><section className="bg-white rounded-xl border p-6"> <h2 className="font-bold text-lg flex gap-2"><Sparkles className="w-5 h-5 text-blue-600"/> AI review</h2>{data.comparison ? <div className="mt-4"><ComparisonMetrics result={data.comparison.result} explanation={data.comparison.explanation} evidenceScore={data.comparison.overall_evidence_score} metrics={{before_area: 0, after_area: 0, reduction_percent: 0}}/></div> : <div className="mt-3 space-y-3"><p className="text-slate-500">Both photos are ready. Run the live Gemini review now.</p>{worker && latestBefore && latestAfter && <button disabled={busy} onClick={runAiReview} className="rounded bg-blue-600 px-4 py-2 font-bold text-white disabled:opacity-50">{busy ? 'Running AI review…' : 'Run AI review now'}</button>}{reviewStatus && <p className="text-sm text-slate-600">{reviewStatus}</p>}</div>}</section></div>;
};
export default PortalComplaintDetail;
